### PR TITLE
getInstaller call was missing a container

### PR DESCRIPTION
**Pull request by GALCF**

### CODE REVIEW

**Comment by ckogler-elements** [comment]
Hi,
i just tried to install it on a Pimcore v10.2.4 (ProcessManger version v4.0.7) and it worked with $this->container...

Normaly $this->container should be available. At least other Bundles are doing it the same way 
https://github.com/pimcore/customer-data-framework/blob/3.x/src/PimcoreCustomerManagementFrameworkBundle.php

Do you still experience this issue?

Regards,
Christian

**Comment by GALCF** [comment]
Sorry, I did not provide enough information, what my issue with it is.

While $this->container is used, the CLI debug:config command does not work for me any more.

**Comment by NiklasBr** [comment]
@ckogler-elements We get the same error with Pimcore 10.2.4:

```
root@6d04c7d3df46:/var/www/pimcore# bin/console config:dump-reference ElementsProcessManagerBundle

# Default configuration for "ElementsProcessManagerBundle"
elements_process_manager:

    # Defines how many days log entries are kept
    archiveThresholdLogs: 7

    # If the MonitoringItem has not been save within X minutes it will be considered as hanging process
    processTimeoutMinutes: 15

    # Disable the shortcut menu on the left side in the Pimcore admin
    disableShortcutMenu:  false

    # Defines email addresses to which errors should be reported
    reportingEmailAddresses: []

    # Defines additional system users which are allowed to execute the php scripts
    additionalScriptExecutionUsers:

        # Default:
        - sdfasdfad@asdfasdf.com
    restApiUsers:

        # Prototype
        -
            username:             ~ # Required
            apiKey:               ~ # Required

13:13:48 CRITICAL  [php] Uncaught Error: Call to a member function get() on null ["exception" => Error { …}]

In ElementsProcessManagerBundle.php line 128:

  Call to a member function get() on null


config:dump-reference [--format FORMAT] [--] [<name> [<path>]]
```

**Comment by ckogler-elements** [comment]
Ok, then lets use this one - thx.

**Pull request merged**
